version: '3'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
      - ./logs:/logs
    command: [ "redis-server", "/etc/redis/redis.conf" ]
