version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
      - 7848:7848
    volumes:
      - ./logs:/home/nacos/logs
    environment:
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.10.30
      - MYSQL_SERVICE_PORT=4006
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - JVM_XMS=1G
      - JVM_XMX=2G
    