version: "3"
services:
   web:
     #定义主机名
     container_name: nginx
     #使用的镜像
     image: nginx:1.16.1
     #容器的映射端口
    #  ports:
    #    - 80:80
    #    - 443:443
     #定义挂载点         
     volumes:
       - ./html:/usr/share/nginx/html
       - ./conf/nginx.conf:/etc/nginx/nginx.conf
       - ./conf.d:/etc/nginx/conf.d
       - ./logs:/var/log/nginx
     #docker 重启后，容器自启动
     restart: always
     network_mode: "host"