# 启动 docker-compose.yml up -d && docker-compose.yml logs -f
# 关闭 docker-compose.yml down &&  docker-compose.yml rm -vf
version: '3.2'
services:
  elasticsearch:
    restart: always
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: "elasticsearch"
    environment:
      # 单节点
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1096m" #设置使用jvm内存大小
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
  kibana:
    image: kibana:7.6.2
    ports:
      - "5601:5601"
    container_name: "kibana"
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
