version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    container_name: minio
    restart: always
    ports:
      # api 端口
      - "9000:9000"
      # 控制台端口
      - "9090:9090"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 管理后台用户名
      MINIO_ROOT_USER: cloudcoding
      # 管理后台密码，最小8个字符
      MINIO_ROOT_PASSWORD: cloudcoding
      # https需要指定域名
      #MINIO_SERVER_URL: "https://xxx.com:9000"
      #MINIO_BROWSER_REDIRECT_URL: "https://xxx.com:9001"
      # 开启压缩 on 开启 off 关闭
      MINIO_COMPRESS: "off"
      # 扩展名 .pdf,.doc 为空 所有类型均压缩
      MINIO_COMPRESS_EXTENSIONS: ""
      # mime 类型 application/pdf 为空 所有类型均压缩
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      # 映射当前目录下的data目录至容器内/data目录
      - ./data:/data
      - ./log:/log
      # 映射配置目录
      - ./config:/root/.minio/
    command: server --address ':9000' --console-address ':9090' /data # 指定容器中的目录 /data
    # network_mode: "host"


